#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: subdomain-finder <example.com>"
  exit 1
fi

extract_subdomain() {
  awk -F: ' { for(i=1 ; i <= NF; ++i) if ($i ~ /name_value/ ) print $(i+1) }' |\
  cut -d "," -f1 |\
  sed 's/"//g' |\
  sed 's/\\n/\n/g' |\
  sed '/^*/d' |\
  sort | uniq  

}

get_subdomains() {
curl https://crt.sh/?q=$1\&output=json | extract_subdomain
}

get_subdomains $1

